name: grpc_web
description: Dart gRPC-Web sample client
publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  grpc:
    path: ../../
  protobuf: ^2.0.0-nullsafety

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1

dependency_overrides:
  # TODO: Need bazel_worker 1.0.0-nullsafety.0 published
  bazel_worker:
    git: https://github.com/dart-lang/bazel_worker
